/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'Sudhanshu' at '7/24/16 12:22 AM' with Gradle 2.13
 *
 * @author Sudhanshu, @date 7/24/16 12:22 AM
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
